// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/example/models.proto

package example_service

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ExampleModel with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ExampleModel) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ExampleModel with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ExampleModelMultiError, or
// nil if none found.
func (m *ExampleModel) ValidateAll() error {
	return m.validate(true)
}

func (m *ExampleModel) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if all {
		switch v := interface{}(m.GetFormedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ExampleModelValidationError{
					field:  "FormedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ExampleModelValidationError{
					field:  "FormedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFormedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ExampleModelValidationError{
				field:  "FormedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ExampleModelMultiError(errors)
	}

	return nil
}

// ExampleModelMultiError is an error wrapping multiple validation errors
// returned by ExampleModel.ValidateAll() if the designated constraints aren't met.
type ExampleModelMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ExampleModelMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ExampleModelMultiError) AllErrors() []error { return m }

// ExampleModelValidationError is the validation error returned by
// ExampleModel.Validate if the designated constraints aren't met.
type ExampleModelValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExampleModelValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExampleModelValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExampleModelValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExampleModelValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExampleModelValidationError) ErrorName() string { return "ExampleModelValidationError" }

// Error satisfies the builtin error interface
func (e ExampleModelValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExampleModel.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExampleModelValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExampleModelValidationError{}
