// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/example/models.proto

package example_service

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExampleModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FormedAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=formed_at,json=formedAt,proto3" json:"formed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExampleModel) Reset() {
	*x = ExampleModel{}
	mi := &file_api_example_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExampleModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleModel) ProtoMessage() {}

func (x *ExampleModel) ProtoReflect() protoreflect.Message {
	mi := &file_api_example_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleModel.ProtoReflect.Descriptor instead.
func (*ExampleModel) Descriptor() ([]byte, []int) {
	return file_api_example_models_proto_rawDescGZIP(), []int{0}
}

func (x *ExampleModel) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ExampleModel) GetFormedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FormedAt
	}
	return nil
}

var File_api_example_models_proto protoreflect.FileDescriptor

const file_api_example_models_proto_rawDesc = "" +
	"\n" +
	"\x18api/example/models.proto\x12\x16api.v1.example_service\x1a\x1fgoogle/protobuf/timestamp.proto\"W\n" +
	"\fExampleModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x127\n" +
	"\tformed_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bformedAtB7Z5github.com/lyceumtech/example-service;example_serviceb\x06proto3"

var (
	file_api_example_models_proto_rawDescOnce sync.Once
	file_api_example_models_proto_rawDescData []byte
)

func file_api_example_models_proto_rawDescGZIP() []byte {
	file_api_example_models_proto_rawDescOnce.Do(func() {
		file_api_example_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_example_models_proto_rawDesc), len(file_api_example_models_proto_rawDesc)))
	})
	return file_api_example_models_proto_rawDescData
}

var file_api_example_models_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_example_models_proto_goTypes = []any{
	(*ExampleModel)(nil),          // 0: api.v1.example_service.ExampleModel
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_api_example_models_proto_depIdxs = []int32{
	1, // 0: api.v1.example_service.ExampleModel.formed_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_example_models_proto_init() }
func file_api_example_models_proto_init() {
	if File_api_example_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_example_models_proto_rawDesc), len(file_api_example_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_example_models_proto_goTypes,
		DependencyIndexes: file_api_example_models_proto_depIdxs,
		MessageInfos:      file_api_example_models_proto_msgTypes,
	}.Build()
	File_api_example_models_proto = out.File
	file_api_example_models_proto_goTypes = nil
	file_api_example_models_proto_depIdxs = nil
}
