// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/example/services.proto

package example_service

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExampleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExampleRequest) Reset() {
	*x = ExampleRequest{}
	mi := &file_api_example_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExampleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleRequest) ProtoMessage() {}

func (x *ExampleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_example_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleRequest.ProtoReflect.Descriptor instead.
func (*ExampleRequest) Descriptor() ([]byte, []int) {
	return file_api_example_services_proto_rawDescGZIP(), []int{0}
}

func (x *ExampleRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type ExampleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objs          []*ExampleModel        `protobuf:"bytes,1,rep,name=objs,proto3" json:"objs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExampleResponse) Reset() {
	*x = ExampleResponse{}
	mi := &file_api_example_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExampleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleResponse) ProtoMessage() {}

func (x *ExampleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_example_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleResponse.ProtoReflect.Descriptor instead.
func (*ExampleResponse) Descriptor() ([]byte, []int) {
	return file_api_example_services_proto_rawDescGZIP(), []int{1}
}

func (x *ExampleResponse) GetObjs() []*ExampleModel {
	if x != nil {
		return x.Objs
	}
	return nil
}

var File_api_example_services_proto protoreflect.FileDescriptor

const file_api_example_services_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/example/services.proto\x12\x16api.v1.example_service\x1a\x1cgoogle/api/annotations.proto\x1a\x18api/example/models.proto\"\"\n" +
	"\x0eExampleRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"K\n" +
	"\x0fExampleResponse\x128\n" +
	"\x04objs\x18\x01 \x03(\v2$.api.v1.example_service.ExampleModelR\x04objs2\x80\x01\n" +
	"\x0eExampleService\x12n\n" +
	"\x03Get\x12&.api.v1.example_service.ExampleRequest\x1a'.api.v1.example_service.ExampleResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/api/v1/getB7Z5github.com/lyceumtech/example-service;example_serviceb\x06proto3"

var (
	file_api_example_services_proto_rawDescOnce sync.Once
	file_api_example_services_proto_rawDescData []byte
)

func file_api_example_services_proto_rawDescGZIP() []byte {
	file_api_example_services_proto_rawDescOnce.Do(func() {
		file_api_example_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_example_services_proto_rawDesc), len(file_api_example_services_proto_rawDesc)))
	})
	return file_api_example_services_proto_rawDescData
}

var file_api_example_services_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_example_services_proto_goTypes = []any{
	(*ExampleRequest)(nil),  // 0: api.v1.example_service.ExampleRequest
	(*ExampleResponse)(nil), // 1: api.v1.example_service.ExampleResponse
	(*ExampleModel)(nil),    // 2: api.v1.example_service.ExampleModel
}
var file_api_example_services_proto_depIdxs = []int32{
	2, // 0: api.v1.example_service.ExampleResponse.objs:type_name -> api.v1.example_service.ExampleModel
	0, // 1: api.v1.example_service.ExampleService.Get:input_type -> api.v1.example_service.ExampleRequest
	1, // 2: api.v1.example_service.ExampleService.Get:output_type -> api.v1.example_service.ExampleResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_example_services_proto_init() }
func file_api_example_services_proto_init() {
	if File_api_example_services_proto != nil {
		return
	}
	file_api_example_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_example_services_proto_rawDesc), len(file_api_example_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_example_services_proto_goTypes,
		DependencyIndexes: file_api_example_services_proto_depIdxs,
		MessageInfos:      file_api_example_services_proto_msgTypes,
	}.Build()
	File_api_example_services_proto = out.File
	file_api_example_services_proto_goTypes = nil
	file_api_example_services_proto_depIdxs = nil
}
