// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/example/services.proto

package example_service

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ExampleRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ExampleRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ExampleRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ExampleRequestMultiError,
// or nil if none found.
func (m *ExampleRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ExampleRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ExampleRequestMultiError(errors)
	}

	return nil
}

// ExampleRequestMultiError is an error wrapping multiple validation errors
// returned by ExampleRequest.ValidateAll() if the designated constraints
// aren't met.
type ExampleRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ExampleRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ExampleRequestMultiError) AllErrors() []error { return m }

// ExampleRequestValidationError is the validation error returned by
// ExampleRequest.Validate if the designated constraints aren't met.
type ExampleRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExampleRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExampleRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExampleRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExampleRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExampleRequestValidationError) ErrorName() string { return "ExampleRequestValidationError" }

// Error satisfies the builtin error interface
func (e ExampleRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExampleRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExampleRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExampleRequestValidationError{}

// Validate checks the field values on ExampleResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ExampleResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ExampleResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ExampleResponseMultiError, or nil if none found.
func (m *ExampleResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ExampleResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetObjs() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ExampleResponseValidationError{
						field:  fmt.Sprintf("Objs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ExampleResponseValidationError{
						field:  fmt.Sprintf("Objs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ExampleResponseValidationError{
					field:  fmt.Sprintf("Objs[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ExampleResponseMultiError(errors)
	}

	return nil
}

// ExampleResponseMultiError is an error wrapping multiple validation errors
// returned by ExampleResponse.ValidateAll() if the designated constraints
// aren't met.
type ExampleResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ExampleResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ExampleResponseMultiError) AllErrors() []error { return m }

// ExampleResponseValidationError is the validation error returned by
// ExampleResponse.Validate if the designated constraints aren't met.
type ExampleResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExampleResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExampleResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExampleResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExampleResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExampleResponseValidationError) ErrorName() string { return "ExampleResponseValidationError" }

// Error satisfies the builtin error interface
func (e ExampleResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExampleResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExampleResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExampleResponseValidationError{}
